import Head from "next/head";
import * as React from "react";

export default function Home() {
  return (
    <>
      <Head>
        <title>Home - Nhà phố sài gòn</title>
        <meta name="description" content="Generated by create home page" />
      </Head>
      <div>
        <h1 className="text-xl font-bold">Hello</h1>
        <h1 className="text-xl font-bold">Hello</h1>
        <h1 className="text-xl font-bold">Hello</h1>
        <h1 className="text-xl font-bold">Hello</h1>
        <h1 className="text-xl font-bold">Hello</h1>
        <h1 className="text-xl font-bold">Hello</h1>
        <h1 className="text-xl font-bold">Hello</h1>
        <h1 className="text-xl font-bold">Hello</h1>
        <h1 className="text-xl font-bold">Hello</h1>
        <h1 className="text-xl font-bold">Hello</h1>
        <h1 className="text-xl font-bold">Hello</h1>
        <h1 className="text-xl font-bold">Hello</h1>
        <h1 className="text-xl font-bold">Hello</h1>
        <h1 className="text-xl font-bold">Hello</h1>
      </div>
    </>
  );
}
